name: Python API Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-html

      # Step 4: Run Pytest and generate HTML report
      - name: Run tests
        run: |
          pytest -v --html=report.html --self-contained-html

      # Step 5: Upload report as build artifact
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.html